COUNTRY_INDEXES = [
    {"country": "United States", "symbol": "^GSPC", "index_name": "S&P 500", "bucket": "developed"},
    {"country": "United States", "symbol": "^IXIC", "index_name": "NASDAQ Composite", "bucket": "developed"},
    {"country": "United States", "symbol": "^DJI", "index_name": "Dow Jones Industrial Average", "bucket": "developed"},
    {"country": "China", "symbol": "000001.SS", "index_name": "Shanghai Composite", "bucket": "emerging"},
    {"country": "China", "symbol": "000300.SS", "index_name": "CSI 300", "bucket": "emerging"},
    {"country": "Germany", "symbol": "^GDAXI", "index_name": "DAX", "bucket": "developed"},
    {"country": "Japan", "symbol": "^N225", "index_name": "Nikkei 225", "bucket": "developed"},
    {"country": "Japan", "symbol": "^TOPX", "index_name": "TOPIX", "bucket": "developed"},
    {"country": "India", "symbol": "^NSEI", "index_name": "Nifty 50", "bucket": "emerging"},
    {"country": "India", "symbol": "^BSESN", "index_name": "BSE Sensex", "bucket": "emerging"},
    {"country": "United Kingdom", "symbol": "^FTSE", "index_name": "FTSE 100", "bucket": "developed"},
    {"country": "France", "symbol": "^FCHI", "index_name": "CAC 40", "bucket": "developed"},
    {"country": "Italy", "symbol": "FTSEMIB.MI", "index_name": "FTSE MIB", "bucket": "developed"},
    {"country": "Canada", "symbol": "^GSPTSE", "index_name": "S&P/TSX Composite", "bucket": "developed"},
    {"country": "Brazil", "symbol": "^BVSP", "index_name": "Bovespa", "bucket": "emerging"},
    {"country": "Russia", "symbol": "IMOEX.ME", "index_name": "MOEX Index", "bucket": "emerging"},
    {"country": "South Korea", "symbol": "^KS11", "index_name": "KOSPI", "bucket": "developed"},
    {"country": "Australia", "symbol": "^AXJO", "index_name": "ASX 200", "bucket": "developed"},
    {"country": "Spain", "symbol": "^IBEX", "index_name": "IBEX 35", "bucket": "developed"},
    {"country": "Mexico", "symbol": "^MXX", "index_name": "IPC Index", "bucket": "emerging"},
    {"country": "Indonesia", "symbol": "^JKSE", "index_name": "Jakarta Composite", "bucket": "emerging"},
    {"country": "Netherlands", "symbol": "^AEX", "index_name": "AEX Index", "bucket": "developed"},
    {"country": "Saudi Arabia", "symbol": "^TASI.SR", "index_name": "Tadawul All Share Index", "bucket": "emerging"},
    {"country": "Turkey", "symbol": "XU100.IS", "index_name": "BIST 100", "bucket": "emerging"},
    {"country": "Switzerland", "symbol": "^SSMI", "index_name": "SMI", "bucket": "developed"},
    {"country": "Poland", "symbol": "^WIG20", "index_name": "WIG20", "bucket": "emerging"},
    {"country": "Sweden", "symbol": "^OMX", "index_name": "OMX Stockholm 30", "bucket": "developed"},
    {"country": "Belgium", "symbol": "^BFX", "index_name": "BEL 20", "bucket": "developed"},
    {"country": "Thailand", "symbol": "^SET.BK", "index_name": "SET Index", "bucket": "emerging"},
    {"country": "Ireland", "symbol": "^ISEQ", "index_name": "ISEQ", "bucket": "developed"},
    {"country": "Argentina", "symbol": "^MERV", "index_name": "MERVAL", "bucket": "emerging"},
    {"country": "Norway", "symbol": "OBX.OL", "index_name": "OBX Index", "bucket": "developed"},
    {"country": "Israel", "symbol": "^TA35", "index_name": "TA-35", "bucket": "developed"},
    {"country": "United Arab Emirates", "symbol": "DFMGI", "index_name": "DFM General Index", "bucket": "emerging"},
    {"country": "Nigeria", "symbol": "NGSEINDEX", "index_name": "NSE All Share Index", "bucket": "emerging"},
]